import Head from 'next/head'
import { Inter } from 'next/font/google'

import fs from 'fs';
import path from 'path';

const inter = Inter({ subsets: ['latin'] })

export default function Home({ data }: { data: { name: string }[] }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={`${inter.className}`}>
        {data.map((item, index) => (
          <div key={index}>{item.name}</div>
        ))}
      </main>
    </>
  )
}

export async function getServerSideProps() {
  const filePath = path.join(process.cwd(), 'config.json');
  const jsonData = fs.readFileSync(filePath, 'utf8');
  const data: { name: string }[] = JSON.parse(jsonData);

  return {
    props: {
      data
    }
  };
}