import Head from 'next/head'
import { Inter } from 'next/font/google'
import { useState, useEffect } from 'react';

import fs from 'fs';
import path from 'path';

const inter = Inter({ subsets: ['latin'] });

export default function Home({ data }: { data: { name: string }[] }) {
  const [imageUrl, setImageUrl] = useState<string>('');
  const [speakerIndex, setSpeakerIndex] = useState<number>(-1);

  useEffect(() => {

    // Image
    (async () => {
      const response = await fetch('/api/image');
      const data = await response.json();
      const imageUrl = data.images[0].url;
      setImageUrl(`http://www.bing.com${imageUrl}`);
    })();

    // State
    setInterval(async () => {
      const response = await fetch('/api/state');
      const data = await response.json();
      setSpeakerIndex(data.speakerIndex);
    }, 500);
  }, []);

  const handleNext = async () => {
    await fetch('/api/state', {
      method: 'PUT',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ speakerIndex: speakerIndex + 1 }),
    });
  };

  const handlePrevious = async () => {
    await fetch('/api/state', {
      method: 'PUT',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ speakerIndex: speakerIndex - 1 }),
    });
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={`${inter.className}`} style={{ backgroundImage: `url(${imageUrl})`, backgroundSize: 'cover' }}>
        <button onClick={handlePrevious}>Previous</button>
        <button onClick={handleNext}>Next</button>
        <div style={{ backgroundColor: 'rgb(40,40,40)', width: '50%', margin: 'auto' }}>
          {data.map((item, index) => (
            <div key={index} style={{
              display: 'flex',
              flexDirection: 'row',
              margin: '10px',
              padding: '10px',
              fontSize: '20px',
              backgroundColor: index === speakerIndex ? 'lightgreen' : 'transparent' // Change the background color here
            }}>
              {item.name}
            </div>
          ))}
        </div>
      </main>
    </>
  )
}

export async function getServerSideProps() {
  const filePath = path.join(process.cwd(), 'config.json');
  const jsonData = fs.readFileSync(filePath, 'utf8');
  const data: { name: string }[] = JSON.parse(jsonData);

  return {
    props: {
      data
    }
  };
}